
## Рабочая тетрадь №1

### 1. Скачать датасет `Students.csv`.

In [66]:
import pandas as pd
import numpy as np

df = pd.read_csv(r'C:\Users\yolff\Downloads\Students.csv')
df.head()

,Student_Name,College_Name,Stream,Year_of_Study,AI_Tools_Used,Daily_Usage_Hours,Use_Cases,Trust_in_AI_Tools,Impact_on_Grades,Do_Professors_Allow_Use,Preferred_AI_Tool,Awareness_Level,Willing_to_Pay_for_Access,State,Device_Used,Internet_Access
0,Aarav,Indian Institute of Information Technology,Engineering,4,Gemini,0.9,"Assignments, Coding Help",2,2,No,Copilot,9,Yes,Uttar pradesh,Mobile,Poor
1,Vivaan,"Government Ram Bhajan Rai NES College, Jashpur",Commerce,2,ChatGPT,3.4,Learning new topics,3,-3,Yes,Other,6,No,Chhattisgarh,Laptop,Poor
2,Aditya,Dolphin PG Institute of BioMedical & Natural,Science,2,Copilot,3.6,"MCQ Practice, Projects",5,0,No,Gemini,1,No,Uttarakhand,Tablet,Poor
3,Vihaan,Shaheed Rajguru College of Applied Sciences for,Arts,2,Copilot,2.9,Content Writing,5,2,Yes,Gemini,5,No,Delhi ncr,Laptop,High
4,Arjun,Roorkee College of Engineering,Science,1,Gemini,0.9,"Doubt Solving, Resume Writing",1,3,Yes,Other,8,Yes,Uttarakhand,Laptop,Medium

### 2. Отфильтровать и вывести отфильтрованные по убыванию стоблец `AI_Tools_Used`.

In [69]:


ai_tools = df['AI_Tools_Used'].dropna()

ai_tools_sorted = ai_tools.sort_values(ascending=False)

ai_tools_sorted

1510    Other
1341    Other
1501    Other
1920    Other
1503    Other
        ...
1052     Bard
1788     Bard
1051     Bard
1786     Bard
1068     Bard
Name: AI_Tools_Used, Length: 3614, dtype: object

### 3. Добавить еще одного студента.
Заполнить столбцы:
- `Stream` и `Device_used` модой распределения;
- `College_Name` новой категорией;
- `Impact_on_Grades` и `Awareness_Level` выборочным средним; 
- `Daily_Usage_Hours` выборочной медианой;
- остальные столбцы заполнить по своему усмотрению.

In [72]:
mode_stream = df['Stream'].mode()[0]
mode_device = df['Device_Used'].mode()[0]
mean_impact = round(df['Impact_on_Grades'].mean(), 2)
mean_awareness = round(df['Awareness_Level'].mean(), 2)
median_usage = df['Daily_Usage_Hours'].median()


new_student = {
    'Student_Name': 'Alex',
    'College_Name': 'Global AI Academy', 
    'Stream': mode_stream,
    'Year_of_Study': 2,
    'AI_Tools_Used': 'ChatGPT, Gemini',
    'Daily_Usage_Hours': median_usage,
    'Use_Cases': 'Research',
    'Trust_in_AI_Tools': 4,
    'Impact_on_Grades': mean_impact,
    'Do_Professors_Allow_Use': 'Yes',
    'Preferred_AI_Tool': 'Gemini',
    'Awareness_Level': mean_awareness,
    'Willing_to_Pay_for_Access': 'No',
    'State': 'International',
    'Device_Used': mode_device,
    'Internet_Access': 'High'
}


df = pd.concat([df, pd.DataFrame([new_student])], ignore_index=True)



df.tail()

,Student_Name,College_Name,Stream,Year_of_Study,AI_Tools_Used,Daily_Usage_Hours,Use_Cases,Trust_in_AI_Tools,Impact_on_Grades,Do_Professors_Allow_Use,Preferred_AI_Tool,Awareness_Level,Willing_to_Pay_for_Access,State,Device_Used,Internet_Access
3610,Rudra,Roorkee College of Pharmacy,Pharmacy,3,Copilot,3.0,Content Writing,2,1.0,No,Copilot,5.00,Yes,NaN,Tablet,Poor
3611,Dhruv,"Bahona College, Jorhat",Agriculture,3,Gemini,2.7,"Exam Prep, Notes",2,1.0,Yes,Copilot,3.00,No,NaN,Tablet,Poor
3612,Kabir,Sree Chitra Thirunal College of Engineering,Engineering,4,Gemini,2.7,"Exam Prep, Notes",3,3.0,Yes,Gemini,3.00,No,NaN,Laptop,High
3613,Atharv,"Poona College of Pharmacy, Pune",Pharmacy,3,Copilot,0.9,"Exam Prep, Notes",1,2.0,No,Copilot,2.00,No,NaN,Mobile,High
3614,Alex,Global AI Academy,Science,2,"ChatGPT, Gemini",2.6,Research,4,0.0,Yes,Gemini,5.83,No,International,Laptop,High

### 4. Произвести кодирование столбцов датасета:
- **Device_used** порядковым кодированием;
- **College_Name** кодированием частотами;
- **Stream** one-hot кодированием

In [75]:
from sklearn.preprocessing import LabelEncoder


label_encoder = LabelEncoder()


df['Device_Used_Label_Encoder'] = label_encoder.fit_transform(df['Device_Used'])


print('Порядковое кодирование :')
    
df[['Device_Used', 'Device_Used_Label_Encoder']].head(10)

Порядковое кодирование :

  Device_Used  Device_Used_Label_Encoder
0      Mobile                          1
1      Laptop                          0
2      Tablet                          2
3      Laptop                          0
4      Laptop                          0
5      Laptop                          0
6      Mobile                          1
7      Mobile                          1
8      Laptop                          0
9      Laptop                          0

In [77]:
from sklearn.preprocessing  import LabelEncoder


label_encoder = LabelEncoder()

df['Device_Used_Label_Encoder'] = label_encoder.fit_transform(df['Device_Used'])
Label_encoder = df['Device_Used_Label_Encoder']

print('Кодирование частотами: ')


df[['Device_Used' , 'Device_Used_Label_Encoder']].head(10)

Кодирование частотами:

  Device_Used  Device_Used_Label_Encoder
0      Mobile                          1
1      Laptop                          0
2      Tablet                          2
3      Laptop                          0
4      Laptop                          0
5      Laptop                          0
6      Mobile                          1
7      Mobile                          1
8      Laptop                          0
9      Laptop                          0

In [98]:

count_dict = df['College_Name'].value_counts().to_dict()


df['College_Name_Encode'] = df['College_Name'].map(count_dict)
college_name = df['College_Name_Encode']


print('ONE-hot кодирование: ')
df[['College_Name' , 'College_Name_Encode']].head(10)

ONE-hot кодирование:

                                        College_Name  College_Name_Encode
0        Indian Institute of Information Technology                    60
1    Government Ram Bhajan Rai NES College, Jashpur                     4
2      Dolphin PG Institute of BioMedical & Natural                     3
3   Shaheed Rajguru College of Applied Sciences for                     6
4                    Roorkee College of Engineering                     2
5                               Kanya Mahavidyalaya                     2
6      Shivalik Institute of Paramedical Technology                     4
7  Alpha College of Engineering & Technology, Pon...                    2
8  Jaipur Engineering College and Research Centre...                    2
9                        ICFAI University, Shillong                     3

### 5. Нормализовать собственными функциями:

* столбeц Daily_Usage_Hours порядковым кодированием;

* вывести медиану столбца Impact_on_Grades;

* вывести перцентили столбца Awareness_Level.

In [91]:
def encode_hours(hours):
    if hours < 2:
        return 0 
    elif hours <= 5:
        return 1 
    else:
        return 2  

df['Daily_Usage_Hours_Ordinal'] = df['Daily_Usage_Hours'].apply(encode_hours)



median_val = df['Impact_on_Grades'].median()

p25 = np.percentile(df['Awareness_Level'], 25)
p50 = np.percentile(df['Awareness_Level'], 50)
p75 = np.percentile(df['Awareness_Level'], 75)


print(f"Медиана Impact_on_Grades: {median_val}")
print(f"Перцентили Awareness_Level: 25% = {p25}, 50% = {p50}, 75% = {p75}")
print("\nТаблица после кодирования (первые 5 строк):")
print(df[['Daily_Usage_Hours', 'Daily_Usage_Hours_Ordinal']].head())

Медиана Impact_on_Grades: 0.0
Перцентили Awareness_Level: 25% = 3.0, 50% = 6.0, 75% = 8.0

Таблица после кодирования (первые 5 строк):
   Daily_Usage_Hours  Daily_Usage_Hours_Ordinal
0                0.9                          0
1                3.4                          1
2                3.6                          1
3                2.9                          1
4                0.9                          0

### 6. Произвести сокращение числа признаков с низкой дисперсией собственной функцией.

In [106]:
import pandas as pd

def filter_low_variance(df, threshold=0.1):
  
    numeric_df = df.select_dtypes(include=['number'])
    
    variances = numeric_df.var()
    
    selected_columns = variances[variances > threshold].index.tolist()
    
    return df[selected_columns]



reduced_df = filter_low_variance(df, threshold=0.1)


print("Таблица признаков с высокой дисперсией:")
print(reduced_df.head())

Таблица признаков с высокой дисперсией:
   Year_of_Study  Daily_Usage_Hours  Trust_in_AI_Tools  Impact_on_Grades  \
0              4                0.9                  2               2.0
1              2                3.4                  3              -3.0
2              2                3.6                  5               0.0
3              2                2.9                  5               2.0
4              1                0.9                  1               3.0

   Awareness_Level  Device_Used_Label_Encoder  College_Name_Encode  \
0              9.0                          1                   60
1              6.0                          0                    4
2              1.0                          2                    3
3              5.0                          0                    6
4              8.0                          0                    2

   Daily_Usage_Hours_Ordinal
0                          0
1                          1
2                          1
3                          1
4                          0